DROP DATABASE IF EXISTS weather;
CREATE DATABASE weather;
USE weather;

CREATE TABLE sensors (
	path CHAR(64) NOT NULL,
	type CHAR(64) NOT NULL,
	subtype CHAR(64),
	PRIMARY KEY (path)
);

CREATE TABLE sensor_entry (
	path CHAR(64) NOT NULL,
	attr CHAR(64) NOT NULL,
	ratio INT NOT NULL DEFAULT 1,
	enable BOOLEAN NOT NULL DEFAULT 0,
	delay MEDIUMINT,
	PRIMARY KEY (path,attr)
);

CREATE TABLE measures (
	id BIGINT NOT NULL AUTO_INCREMENT,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	sync BOOLEAN NOT NULL DEFAULT 0,
	path CHAR(64) NOT NULL,
	attr CHAR(64) NOT NULL,
	value FLOAT NOT NULL,
	PRIMARY KEY (id)
);

GRANT ALL PRIVILEGES ON *.* TO 'weather'@'localhost' IDENTIFIED BY 'weather43'  WITH GRANT OPTION;
